<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abhishek-PC" name="com.asda.groceries.testngscripts.Test_login_user" tests="5" failures="1" timestamp="3 Jan 2015 22:48:28 GMT" time="3.532" errors="0">
  <testcase name="test2" time="0.002" classname="com.asda.groceries.testngscripts.Test_login_user"/>
  <testcase name="test4" time="0.003" classname="com.asda.groceries.testngscripts.Test_login_user"/>
  <testcase name="test1" time="0.010" classname="com.asda.groceries.testngscripts.Test_login_user"/>
  <testcase name="login_test" time="3.515" classname="com.asda.groceries.testngscripts.Test_login_user">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;tru...&gt; but was:&lt;fals...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<tru...> but was:<fals...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.asda.groceries.testngscripts.Test_login_user.login_test(Test_login_user.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- login_test -->
  <testcase name="test3" time="0.002" classname="com.asda.groceries.testngscripts.Test_login_user"/>
</testsuite> <!-- com.asda.groceries.testngscripts.Test_login_user -->
